### PR TITLE
Adds missing client_secret to the auth params

### PR DESCRIPTION
**Pull request by cavewoman**

### CODE REVIEW

**Comment by radzserg** [comment]
This PR is correct. https://www.instagram.com/developer/authentication/ client secret must be provided. Current version of ueberauth_instagram - doesn't work without this PR. Please merge.

**Comment by janetruluck** [comment]
@radzserg thanks for the bump and @cavewoman thanks for the PR. I will get this in ASAP

**Comment by radzserg** [comment]
:+1:  but you need to bump a version. Otherwise you still get old version. Works if only you sepcify `{:ueberauth_instagram, git: "https://github.com/jasontruluck/ueberauth_instagram"},`

**Comment by janetruluck** [comment]
Hey @radzserg the version should have been bumped [here](https://github.com/jasontruluck/ueberauth_instagram/commit/5f3a24fb15e73649463d6252c506ad89267b0eb5) and it looks like hex is seeing it as v 0.2.0. Maybe there is another issue?

**Comment by radzserg** [comment]
Cool. It works. BTW don't forget to update README so other know that there's new version ;)

**Pull request merged**
